# ansible-playbook -i ~/ansible/hosts /playbooks/new-default.yml
---
- hosts: defaultdevices
  gather_facts: yes
  vars:
    hostname: your_hostname
    wifi_ssid: your_ssid
    wifi_password: your_wifi_password
    wifi_country: "US"
    locale: "en_US.UTF-8"
    keyboard: "pc104"
    keyboard_layout: "us"
    timezone: America/Los_Angeles
    locale_options:
      # Disable Default (GB) Locale
      - regexp: "^#?en_GB.UTF-8 UTF-8"
        line: "# en_GB.UTF-8 UTF-8"
      # Enable US Locale
      - regexp: "^#?en_US.UTF-8 UTF-8"
        line: "en_US.UTF-8 UTF-8"

  tasks:

    # Expand the filesystem
    - include_tasks: ../tasks/expand-filesystem.yml
      tags: setup

    # Set Internationalization Options
    - include_tasks: ../tasks/internationalization.yml
      tags: setup

    # Set WiFi Options
    - include_tasks: ../tasks/wifi.yml
      tags: setup

    - name: run 'dpkg --configure -a'
      become: yes
      command: dpkg --configure -a

    # Run apt-get update and apt-get upgrade 

    # Update apt packages
    - name: Update apt packages
      become: yes
      apt: 
        update_cache=yes

    # Upgrade apt packages
    - name: Upgrade apt packages
      become: yes
      apt: 
        upgrade=dist

    # Set the hostname
    - name: Set the hostname
      become: yes
      command: hostnamectl set-hostname "{{ hostname }}"

    # Set the hostname in /etc/hosts too
    - name: Set the other hostname
      become: yes
      command: sed -i "s/127.0.1.1.*raspberrypi/127.0.1.1\t{{ hostname }}/g" /etc/hosts

    - include_tasks: ../tasks/tzdata.yml
      tags: system