
# ansible-playbook -i ~/ansible/hosts /playbooks/solus-desktop.yml
---
- hosts: linuxboxes
  gather_facts: yes
  vars:
    wifi_country: "US"

  tasks:

    # Third Party Software
    - name: Download Microsoft fonts spec
      become: yes
      command: eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/desktop/font/mscorefonts/pspec.xml
    - name: Install Microsoft fonts
      become: yes
      command: eopkg it mscorefonts*.eopkg

    - name: Download Google Chrome spec
      become: yes
      command: eopkg bi --ignore-safety eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/network/web/browser/google-chrome-stable/pspec.xml
    - name: Install Google Chrome
      become: yes
      command: eopkg it google-chrome-*.eopkg

    - name: Download Skype for Linux spec
      become: yes
      command: eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/network/im/skype/pspec.xml
    - name: Install Skype for Linux
      become: yes
      command: sudo eopkg it skype*.eopkg;rm *.eopkg

    # Git 
    - name: Install Git
      become: yes
      command: eopkg install git
    - name: Enable colors in git output
      become: yes
      command: git config --global color.ui auto

    - name: Install VS Code
      become: yes
      command: eopkg install vscode
    - name: Install Terminator
      become: yes
      command: eopkg install terminator
    - name: Install Angry IP Scanner
      become: yes
      command: eopkg install ipscan

  handlers:

    - include: ../handlers/reboot.yml
      tags: system

  
